### PR TITLE
Jamulus.pro jackonwindows support improvements

### PR DESCRIPTION
**Pull request by jujudusud**
#1705 
Work in progress -> Jamulus.pro for windows 10 64 bits + JACK on Windows build.
Need help to make the magic append.

### CODE REVIEW

File: Jamulus.pro [hunk 1]
```diff
@@ -109,6 +109,51 @@ win32 {
         INCLUDEPATH += "C:/Program Files (x86)/Jack/includes"
         LIBS += "C:/Program Files (x86)/Jack/lib/libjack64.lib"
     }
+} else:win64 {
```
Comment (hoffie) [inline Jamulus.pro:112]: Is there an actual `win64` target?

Can't just use a `contains(QT_ARCH, x86_64)` conditional within the existing `win32` target? This should simplify the logic a lot and should save duplication if the sole intention is to change the jack path.

File: Jamulus.pro [hunk 2]
```diff
@@ -109,6 +109,51 @@ win32 {
...
+            advapi32.lib \
+            winmm.lib \
+            ws2_32.lib
+    }
+
+    # replace ASIO with jack if requested
+    contains(CONFIG, "jackonwindows") {
+        message(Using Jack instead of ASIO.)
+
+        !exists("C:/Program Files/JACK2/includes/jack/jack.h") {
```
Comment (hoffie) [inline Jamulus.pro:143]: If possible, it may make sense to define some JACK_BASE_PATH variable and derive all other paths from that?

File: Jamulus.pro (hunk 1 above)
Comment (henkdegroot) [reply Jamulus.pro:112]: @jujudusud , please note that the path for the jack include folder is now named include (without the s).
When I build the version locally with jackonwindows, I used the contains(QT_ARCH, x86_x64) which I believe saves duplicating/maintaining extra lines. And perhaps the message prompted that jack is not installed could change to "Warning: jack.h was not found at the usual place, maybe jack is not installed or it is not the latest version"

Thanks for doing this...I could have done it as well, but was waiting for feedback on the issue regarding the approach to take.

**Comment by henkdegroot** [comment]
@jujudusud  here is the Jamulus.pro file I have used to build. Please note this contains the "jackonwindows" option in the CONFIG section, so only use the jack part in the win32 section please.
[Jamulus.pro.txt](https://github.com/jamulussoftware/jamulus/files/6506204/Jamulus.pro.txt)

File: Jamulus.pro (hunk 1 above)
Comment (jujudusud) [reply Jamulus.pro]: Now using `win32` target and `contains(QT_ARCH, x86_64)` conditional.
Thanks for reviewing and helping.

File: Jamulus.pro (hunk 2 above)
Comment (npostavs) [reply Jamulus.pro]: I think it would work like this:
```
        contains(QT_ARCH, "x86") {
            jack_dir = "C:/Program Files (x86)/Jack"
        } else {
            jack_dir = "C:/Program Files/Jack"
        }

        !exists($${jack_dir}/includes/jack/jack.h) {
            message(Warning: jack.h was not found at the usual place, maybe jack is not installed)
        }
```

```
        INCLUDEPATH += $${jack_dir}/includes"
        LIBS += $${jack_dir}/lib/libjack64.lib
```

Comment (jujudusud) [reply Jamulus.pro]: do you think it is possible to use Windows environment variable instead of the hard coded one ?
Something like : `%ProgramFiles%` or the `ProgramFilesDir` key used in registry ?

Comment (npostavs) [reply Jamulus.pro]: To access `%ProgramFiles(x86)%` we would need [`getenv`](https://doc.qt.io/qt-5/qmake-function-reference.html#getenv-variablename), which requires Qt 5.12 (might be okay, I think there's already a proposal to bump min Qt version for Mac).

```
        contains(QT_ARCH, "x86") {
            jack_dir = $$getenv("ProgramFiles(x86)")/Jack
        } else {
            jack_dir = $$getenv("ProgramFiles")/Jack
        }
```

Comment (henkdegroot) [reply Jamulus.pro]: Autobuild script for Windows is using Qt 5.15.2 already as well, so it should not be a problem to use getenv.

File: Jamulus.pro [hunk 3]
```diff
@@ -95,20 +95,39 @@ win32 {
     contains(CONFIG, "jackonwindows") {
         message(Using Jack instead of ASIO.)
 
-        !exists("C:/Program Files (x86)/Jack/includes/jack/jack.h") {
-            message(Warning: jack.h was not found at the usual place, maybe jack is not installed)
+        contains(QT_ARCH, "x86") {
```
Comment (pljones) [inline Jamulus.pro:98]: If I install Windows 32bit, isn't "Program Files" where 32bit programs live?

I thought "Program Files (x86)" only existed on Windows 64bit systems (where "Program Files" is for 64bit programs and "Programs Files (x86)" for 32bit).

File: Jamulus.pro [hunk 4]
```diff
@@ -95,20 +95,39 @@ win32 {
...
+		    !exists("C:/Program Files (x86)/JACK2/includes/jack/jack.h") {
+                message(Warning: jack.h was not found at the usual place, maybe jack2 32-bit is not installed)
+            }
+
+            HEADERS -= windows/sound.h
```
Comment (pljones) [inline Jamulus.pro:103]: Get rid of this duplication.

File: Jamulus.pro (hunk 2 above)
Comment (hoffie) [reply Jamulus.pro]: > which requires Qt 5.12 (might be okay, I think there's already a proposal to bump min Qt version for Mac).

I think we only agreed to bump the Qt version for the official builds. We did not drop support for building with older versions of Qt, as far as I know.

File: Jamulus.pro (hunk 3 above)
Comment (jujudusud) [reply Jamulus.pro:98]: I don't know. If anyone can say something about that. 
(jujudusud is thinking of Microsoft just deprecated 32 bits windows 10...)
Anyway, If this is wrong I will change this line. Thanks for the review !

File: Jamulus.pro (hunk 4 above)
Comment (jujudusud) [reply Jamulus.pro:103]: To get rid of this duplication, I will also have to use a `lib-name` variable. This variable should return :

- libjack64.lib for x86_64,
- libjack.lib for x86.

So ... Will do when it's ok in my head.

File: Jamulus.pro (hunk 3 above)
Comment (henkdegroot) [reply Jamulus.pro:98]: > If I install Windows 32bit, isn't "Program Files" where 32bit programs live?
> 
> I thought "Program Files (x86)" only existed on Windows 64bit systems (where "Program Files" is for 64bit programs and "Programs Files (x86)" for 32bit).

That is correct, as long as you compile/build on the solution on a 64-bit system then this should not be an issue.

File: Jamulus.pro (hunk 2 above)
Comment (henkdegroot) [reply Jamulus.pro]: @jujudusud the line:  !exists("C:/Program Files/JACK2/includes/jack/jack.h")
is incorrect referring to /includes/ here...it should be /include/  

Reason I did not notice is because the "message" function is throwing an error.

 message(Warning: jack.h was not found at the usual place, maybe jack is not installed)

This is generating an error due to the , (comma) in the text. The error says that message requires one argument.
Either replace the , by another character or use "" around the text in the message.
Also as it is just a "message" it does not even stop the build process.

This "message" issue also appears in the "macx" section. Perhaps this can be adapted as well? Assuming the title of the PR should change in that case.

File: Jamulus.pro (hunk 3 above)
Comment (pljones) [reply Jamulus.pro:98]: If you're building Jamulus x64, then we want JACK x64 (which will be under "Program Files" on x64).  QT_ARCH won't be "x86".

The main reason anyone would be building x86 would be if they were building on x86 and want JACK x86 (which will be under "Program Files" on x86).  QT_ARCH will be "x86".

The only time to use "Program Files (x86)", then, is if cross-compiling from x64 to x86.  However, QT_ARCH alone doesn't tell you this, from what I can see?

Comment (pljones) [reply Jamulus.pro:98]: So...

If QT_ARCH = x86
* If  "Program Files (x86)" exists, it's a cross-compile - set the install dir to "Program Files (x86)"
* Otherwise set the install dir to "Program Files"
* Set the x86-specific bits

Else
* Set the install dir to "Program Files"
* Set the x64-specific bits

Check the install is sane.

Comment (henkdegroot) [reply Jamulus.pro:98]: @pljones when you build the instapper for Windows, it includes both the x86 and x86_x64 application in it. When installing this the appropiate version for your pc will be installen. So you need to be able to have both options at the same time.

File: Jamulus.pro (hunk 2 above)
Comment (jujudusud) [reply Jamulus.pro]: What about 'read_registry(tree, key[, flag])' instead of getenv ?
'read_registry(HKLM, ProgramFilesDir[, 64])'
Should return the good path for 64bits.

Comment (henkdegroot) [reply Jamulus.pro]: My view is...why make it so complex? As JACK might even have been installed somewhere else....I would say it is a slight overkill to include all this. Not that is isn't nice to have it...

Comment (hoffie) [reply Jamulus.pro]: > My view is...why make it so complex? As JACK might even have been installed somewhere else..

I agree. The compromise I'd aim for would be: Make sure the default works and provide a way to override for builds against different paths (`qmake JACK_INSTALL_DIR=/path/to/jack` -- maybe there are existing conventions what the variable should be named).

Comment (henkdegroot) [reply Jamulus.pro]: > qmake JACK_INSTALL_DIR=/path/to/jack

That would also be beneficial in case we want to setup an automated build. Not sure how such script would install jack...but with the variable it could become an option to consider.

Comment (jujudusud) [reply Jamulus.pro]: this is the use of read registry
`    # replace ASIO with jack if requested
    contains(CONFIG, "jackonwindows") {
        message(Using Jack instead of ASIO.)

        contains(QT_ARCH, "x86") {
        	ProgramFilesDir = read_registry(HKLM, ProgramFilesDir[, 32])
		    !exists("$${ProgramFilesDir}/JACK2/include/jack/jack.h") {
                message(Warning: "jack.h was not found at the usual place, maybe JACK2 is not installed")
            }

            HEADERS -= windows/sound.h
            SOURCES -= windows/sound.cpp
            HEADERS += linux/sound.h
            SOURCES += linux/sound.cpp
            DEFINES += WITH_JACK
            DEFINES += JACK_REPLACES_ASIO
            DEFINES += _STDINT_H # supposed to solve compilation error in systemdeps.h
            INCLUDEPATH += "$${ProgramFilesDir}/JACK2/include"
            LIBS += "$${ProgramFilesDir}/JACK2/lib/libjack.lib"
        }

        contains(QT_ARCH, "x86_64") {
		    ProgramFilesDir = read_registry(HKLM, ProgramFilesDir[, 64])
		    !exists("$${ProgramFilesDir}/JACK2/include/jack/jack.h") {
                message(Warning: "jack.h was not found at the usual place, maybe JACK2 64-bit is not installed")
            }

            HEADERS -= windows/sound.h
            SOURCES -= windows/sound.cpp
            HEADERS += linux/sound.h
            SOURCES += linux/sound.cpp
            DEFINES += WITH_JACK
            DEFINES += JACK_REPLACES_ASIO
            DEFINES += _STDINT_H # supposed to solve compilation error in systemdeps.h
            INCLUDEPATH += "$${ProgramFilesDir}/JACK2/include"
            LIBS += "$${ProgramFilesDir}/JACK2/lib/libjack64.lib"
        }`

File: Jamulus.pro (hunk 4 above)
Comment (jujudusud) [reply Jamulus.pro:103]: `        contains(QT_ARCH, "x86") {
        	ProgramFilesDir = read_registry(HKLM, ProgramFilesDir[, 32])
        	libjack-name = libjack.lib
		    !exists("$${ProgramFilesDir}/JACK2/include/jack/jack.h") {
                message(Warning: "jack.h was not found at the usual place, maybe JACK2 is not installed")
            }

            HEADERS -= windows/sound.h
            SOURCES -= windows/sound.cpp
            HEADERS += linux/sound.h
            SOURCES += linux/sound.cpp
            DEFINES += WITH_JACK
            DEFINES += JACK_REPLACES_ASIO
            DEFINES += _STDINT_H # supposed to solve compilation error in systemdeps.h
            INCLUDEPATH += "$${ProgramFilesDir}/JACK2/include"
            LIBS += "$${ProgramFilesDir}/JACK2/lib/$${libjack-name}"
        }

        contains(QT_ARCH, "x86_64") {
		    ProgramFilesDir = read_registry(HKLM, ProgramFilesDir[, 64])
		    libjack-name = libjack64.lib
		    !exists("$${ProgramFilesDir}/JACK2/include/jack/jack.h") {
                message(Warning: "jack.h was not found at the usual place, maybe JACK2 64-bit is not installed")
            }

            HEADERS -= windows/sound.h
            SOURCES -= windows/sound.cpp
            HEADERS += linux/sound.h
            SOURCES += linux/sound.cpp
            DEFINES += WITH_JACK
            DEFINES += JACK_REPLACES_ASIO
            DEFINES += _STDINT_H # supposed to solve compilation error in systemdeps.h
            INCLUDEPATH += "$${ProgramFilesDir}/JACK2/include"
            LIBS += "$${ProgramFilesDir}/JACK2/lib/$${libjack-name}"
        }`

File: Jamulus.pro (hunk 3 above)
Comment (jujudusud) [reply Jamulus.pro:98]: I don't how to code this into the Jamulus.pro file.

File: Jamulus.pro (hunk 2 above)
Comment (jujudusud) [reply Jamulus.pro]: ok ! think  it will be ok with 
c0a5110

File: Jamulus.pro (hunk 4 above)
Comment (jujudusud) [reply Jamulus.pro]: c0a5110

File: Jamulus.pro (hunk 3 above)
Comment (jujudusud) [reply Jamulus.pro:98]: Ok with :
c0a5110

**Comment by pljones** [comment]
Maybe something like this would work - not tried it:
```
contains(CONFIG, "jackonwindows") {
  contains(QT_ARCH, "x86") {
    !exists("C:/Program Files (x86)/") {
      message(Native x86 build)
  	ProgramFilesDir = "C:/Program Files"
    } else {
      message(Cross-compile x86 build)
  	ProgramFilesDir = "C:/Program Files (x86)"
    }
    libjack-name = libjack.lib
  } else {
    libjack-name = libjack64.lib
  }
  !exists("$${ProgramFilesDir}/JACK2/include/jack/jack.h") {
    message("Warning: jack.h was not found at the usual place, maybe JACK2 is not installed.  Reverting to ASIO.")
	CONFIG -= "jackonwindows"
  } else {
    message(Using Jack instead of ASIO.)

    HEADERS -= windows/sound.h
    SOURCES -= windows/sound.cpp
    HEADERS += linux/sound.h
    SOURCES += linux/sound.cpp
    DEFINES += WITH_JACK
    DEFINES += JACK_REPLACES_ASIO
    DEFINES += _STDINT_H # supposed to solve compilation error in systemdeps.h
    INCLUDEPATH += "$${ProgramFilesDir}/JACK2/include"
    LIBS += "$${ProgramFilesDir}/JACK2/lib/$${libjack-name}"
  }
}
```

File: ChangeLog [hunk 5]
```diff
@@ -38,8 +38,6 @@
   (contributed by @vimpostor)
 
 - The term "Central server" has been replaced with "Directory server" (#1407).
-  Note that the program will still accept the --centralserver option for backward
-  compatibility with existing system startup scripts.
```
Comment (hoffie) [inline ChangeLog:42]: Hrm, might be an indicator for a partially bad merge/rebase?

File: Jamulus.pro [hunk 6]
```diff
@@ -95,20 +95,28 @@ win32 {
...
+        	ProgramFilesDir = read_registry(HKLM, ProgramFilesDir[, 32])
+        	libjack-name = libjack.lib
+        } else {
+            ProgramFilesDir = read_registry(HKLM, ProgramFilesDir[, 64])
+		    libjack-name = libjack64.lib	
+          }
+          !exists("$${ProgramFilesDir}/JACK2/include/jack/jack.h") {
+            message("Warning: jack.h was not found at the usual place, maybe JACK2 is not installed")
+          }
+
```
Comment (hoffie) [inline Jamulus.pro:108]: Indentation seems to be off here and further below.

File: src/res/translation/translation_fr_FR.ts [hunk 7]
```diff
@@ -1367,17 +1367,17 @@ Nous avons coupé votre canal et activé &quot;Me silencer&quot;. Veuillez d&apo
     <message>
         <location filename="../../clientsettingsdlg.cpp" line="250"/>
         <source>Language</source>
-        <translation>Langue</translation>
+        <translation type="unfinished">Langue</translation>
```
Comment (hoffie) [inline src/res/translation/translation_fr_FR.ts:1370]: The .ts files should not show up in this PR. The PR seems to revert those files to an earlier status.

File: Jamulus.pro [hunk 8]
```diff
@@ -95,20 +95,28 @@ win32 {
     contains(CONFIG, "jackonwindows") {
         message(Using Jack instead of ASIO.)
 
-        !exists("C:/Program Files (x86)/Jack/includes/jack/jack.h") {
-            message(Warning: jack.h was not found at the usual place, maybe jack is not installed)
-        }
+        contains(QT_ARCH, "x86") {
```
Comment (hoffie) [inline Jamulus.pro:98]: Has this been tested?
I'd assume that `contains(x86_64, x86)` and `contains(x86, x86)` will both be true?
[`equals()`](https://doc.qt.io/qt-5/qmake-test-function-reference.html#equals-variablename-value) looks more correct to me for this use case.

File: Jamulus.pro [hunk 9]
```diff
@@ -95,20 +95,28 @@ win32 {
...
+        	ProgramFilesDir = read_registry(HKLM, ProgramFilesDir[, 32])
```
Comment (hoffie) [inline Jamulus.pro:99]: As @henkdegroot mentioned, `read_registry` seems to be a [fairly recent Qt addition](https://doc.qt.io/qt-5/qmake-function-reference.html#read-registry-tree-key-flag). Adding this function call will likely break things for pre-5.12.1 Qt users.

Is this really necessary? It's a trade-off between compatibility with earlier Qt and covering even more cases. The existing code uses hardcoded paths as well and nobody seems to have complained, so I'd rather suggest to keep it simple and avoid introducing downsides by doing this?

**Review by hoffie — CHANGES_REQUESTED** [review]
- Can you update the PR title to cover the fact that it re-works jack path handling?
- There seem to be git merge/rebase problems. If we squash-merge later, history within this PR should not be too important, so you could probably fix it like this:
  - `git fetch upstream` to ensure that you've got the latest master commits in your clone
  - `git checkout upstream/master Changelog src/res/translation/` to revert the modified files' content to what's currently in master
  - `git commit -m "Fix unintended master reverts" ,` to commit those reverts.
-  (Possible) break of compatibility with earlier Qt would be good to avoid.

File: Jamulus.pro (hunk 8 above)
Comment (henkdegroot) [reply Jamulus.pro:98]: > I'd assume that `contains(x86_64, x86)` and `contains(x86, x86)` will both be true?

Interesting spot! I have checked, and while it was working on my system when I compiled it...it sounds as if it was just working by luck.

When the build is performed on windows for 64-bit, the QT_ARCH is set to "x86_64".
When the build is performed on windows for 32-bit, the QT_ARCH is set to "i386"

So the jamulus.pro needs updating for this.

Comment (jujudusud) [reply Jamulus.pro:98]: What about Windows 64 bits in 32 bits mode ? WOW64 let the user work in 32 bits mode. Is the QT_ARCH set to 'x86_64' in this case ?

That's why I wanna add a target first with win64 label... ;-)

File: Jamulus.pro (hunk 9 above)
Comment (jujudusud) [reply Jamulus.pro:99]: Ok.
On Windows, the user can use the latest QT développement environnement to build and I think it's better to say : Hey, please use the latest environnement.
We are talking about 1% of the user on Windows who will build there own Jamulus app...
I will hard code but don't like that.

File: src/res/translation/translation_fr_FR.ts (hunk 7 above)
Comment (jujudusud) [reply src/res/translation/translation_fr_FR.ts:1370]: I think I made a mistake Yesterday.
I will solve that. Thanks

File: ChangeLog (hunk 5 above)
Comment (jujudusud) [reply ChangeLog:42]: My bas. Will solve.

Comment (jujudusud) [reply ChangeLog]: Solved by 
5aa0168

File: Jamulus.pro (hunk 6 above)
Comment (jujudusud) [reply Jamulus.pro]: ok in
5aa0168

File: src/res/translation/translation_fr_FR.ts (hunk 7 above)
Comment (jujudusud) [reply src/res/translation/translation_fr_FR.ts]: solved 
5aa0168

File: Jamulus.pro (hunk 8 above)
Comment (jujudusud) [reply Jamulus.pro]: Think it's ok in the last commit:
5aa0168

File: Jamulus.pro (hunk 9 above)
Comment (jujudusud) [reply Jamulus.pro]: Hard coded in the last commit:
5aa0168

**Comment by jujudusud** [comment]
Ready to be merged.

File: Jamulus.pro [hunk 10]
```diff
@@ -93,22 +93,31 @@ win32 {
 
     # replace ASIO with jack if requested
     contains(CONFIG, "jackonwindows") {
-        message(Using Jack instead of ASIO.)
-
-        !exists("C:/Program Files (x86)/Jack/includes/jack/jack.h") {
-            message(Warning: jack.h was not found at the usual place, maybe jack is not installed)
+        contains(QT_ARCH, "i386") {
```
Comment (pljones) [inline Jamulus.pro:96]: The indentation here is all over the place, making it very hard to read what's intended.  Please make sure only spaces are used (for example, there are leading tabs on many lines).

File: Jamulus.pro [hunk 11]
```diff
@@ -93,22 +93,31 @@ win32 {
...
+        	message("Native i386 build")
```
Comment (pljones) [inline Jamulus.pro:97]: Is this correct?  What if I'm running Windows 64-bit but a 32bit compile?  That's _not_ a native i386 build.

File: Jamulus.pro [hunk 12]
```diff
@@ -93,22 +93,31 @@ win32 {
...
+        	libjackname = libjack.lib
```
Comment (pljones) [inline Jamulus.pro:98]: Why is there no check for `jack.h` for 32bit?

File: Jamulus.pro [hunk 13]
```diff
@@ -93,22 +93,31 @@ win32 {
...
+        } else {
+        	message("Native x86_64 build")
+		    libjackname = libjack64.lib
+		    !exists("C:/Program Files (86)/JACK2/include/jack/jack.h") {
+            	message("Warning: jack.h was not found at the usual place, install JACK2 32 bits to cross compile.")
```
Comment (pljones) [inline Jamulus.pro:103]: The message above says this is a native compile.  Here, you're saying it's a cross-compile.  This seems confused.

File: Jamulus.pro [hunk 14]
```diff
@@ -93,22 +93,31 @@ win32 {
...
+         	}	
         }
+          !exists("C:/Program Files/JACK2/include/jack/jack.h") {
```
Comment (pljones) [inline Jamulus.pro:106]: This check appears to be happening regardless of whether on 32 or 64bit.

File: Jamulus.pro (hunk 11 above)
Comment (jujudusud) [reply Jamulus.pro:97]: I would say If you are running a Windows 64 bits, QT_ARCH will be set to `x86_64`.

File: Jamulus.pro (hunk 13 above)
Comment (jujudusud) [reply Jamulus.pro:103]: No, If `C:\Program Files (x86)` exist then you cross compile .

File: Jamulus.pro (hunk 10 above)
Comment (jujudusud) [reply Jamulus.pro:96]: Sorry, my bad.
087f835

File: Jamulus.pro (hunk 12 above)
Comment (jujudusud) [reply Jamulus.pro]: At line 106.

File: Jamulus.pro (hunk 14 above)
Comment (jujudusud) [reply Jamulus.pro:106]: That's right. `jack.h` is at the same place whether you are in 32 bits or 64 bits Windows OS.
64 bits is  - > `C:/Program Files/JACK2/include/jack/jack.h` + eventually if 32 bits is installed `C:/Program Files (86)/JACK2/include/jack/jack.h`
where 32 bits is "only" -> `C:/Program Files/JACK2/include/jack/jack.h`

File: Jamulus.pro [hunk 15]
```diff
@@ -94,19 +94,19 @@ win32 {
...
-         	}	
+            message("Native x86_64 build")
+            libjackname = libjack64.lib
+            !exists("C:/Program Files (86)/JACK2/include/jack/jack.h") {
+                message("Warning: jack.h was not found at the usual place, install JACK2 32 bits to cross compile.")
+            }
         }
           !exists("C:/Program Files/JACK2/include/jack/jack.h") {
-         	 message("Warning: jack.h was not found at the usual place, maybe JACK2 64 bits to compile")
+            message("Warning: jack.h was not found at the usual place, maybe JACK2 64 bits to compile")
```
Comment (henkdegroot) [inline Jamulus.pro:107]: This message is not correct. This shows for both cases (x86_64 and i386). But when you build on a 32-bit platform, you should install the 32-bit JACK version. Perhaps extend the text with this information? Something like "install JACK2 32/64 bits depending on your OS architecture to compile"
Also the text "maybe JACK2" would be more accurate if it is "install JACK2".

**Review by henkdegroot — CHANGES_REQUESTED** [review]

File: Jamulus.pro [hunk 16]
```diff
@@ -93,22 +93,31 @@ win32 {
...
-
-        !exists("C:/Program Files (x86)/Jack/includes/jack/jack.h") {
-            message(Warning: jack.h was not found at the usual place, maybe jack is not installed)
+        contains(QT_ARCH, "i386") {
+            message("Native i386 build")
+            libjackname = libjack.lib
+        } else {
+            message("Native x86_64 build")
+            libjackname = libjack64.lib
+            !exists("C:/Program Files (86)/JACK2/include/jack/jack.h") {
```
Comment (henkdegroot) [inline Jamulus.pro:102]: "C:/Program Files (86)/JACK2/include/jack/jack.h" is missing an x, it should be

C:/Program Files (**x**86)/JACK2/include/jack/jack.h

Comment (jujudusud) [reply Jamulus.pro]: Ok in 02db193

File: Jamulus.pro (hunk 15 above)
Comment (jujudusud) [reply Jamulus.pro]: Modified in 02db193

File: Jamulus.pro [hunk 17]
```diff
@@ -116,7 +116,7 @@ win32 {
             DEFINES += _STDINT_H # supposed to solve compilation error in systemdeps.h
             INCLUDEPATH += "C:/Program Files/JACK2/include"
             LIBS += "C:/Program Files/JACK2/lib/$${libjackname}"
```
Comment (henkdegroot) [inline Jamulus.pro:118]: @jujudusud , the LIBS value needs to set different when cross compiling (x86/i386 in a 64-bit Win OS). Current an error is generated when the lib is linked as it cannot find the **libjack.lib** in the folder "C:/Program Files/JACK2/lib/", as it is located in the "C:/Program Files (x86)/JACK2/lib/" folder.

Comment (jujudusud) [reply Jamulus.pro:118]: That's why I said we have to had a win64 target...
Do you know how to fix that ?

File: Jamulus.pro [hunk 18]
```diff
@@ -93,22 +93,31 @@ win32 {
...
+            SOURCES -= windows/sound.cpp
+            HEADERS += linux/sound.h
+            SOURCES += linux/sound.cpp
+            DEFINES += WITH_JACK
+            DEFINES += JACK_REPLACES_ASIO
+            DEFINES += _STDINT_H # supposed to solve compilation error in systemdeps.h
+            INCLUDEPATH += "C:/Program Files/JACK2/include"
+            LIBS += "C:/Program Files/JACK2/lib/$${libjackname}"
     }
+
```
Comment (hoffie) [inline Jamulus.pro:120]: Just a quick note (haven't looked at the other recent updates yet): Indentation still seems to be off.

Comment (jujudusud) [reply Jamulus.pro]: I think it is ok in 506876e4

File: Jamulus.pro (hunk 17 above)
Comment (jujudusud) [reply Jamulus.pro]: is it ok with the 506876e4 commit ?

File: Jamulus.pro [hunk 19]
```diff
@@ -93,10 +93,29 @@ win32 {
...
+                message ("Cross compilation build")
+                programfilesdir = "C:/Program Files (x86)"
+                !exists("$${"programfilesdir"}/JACK2/include/jack/jack.h") {
+                    message("Warning: jack.h was not found at the usual place, maybe JACK2 32 bits is not installed to cross compile.")
+                }
+            }
+            !exist("C:/Program Files") {
+                message("Native i386 build")
+                programfilesdir = "C:/Program Files"
+                !exists("$${"programfilesdir"}/JACK2/include/jack/jack.h") {
```
Comment (hoffie) [inline Jamulus.pro:107]: Should this rather be an `else` branch to the previous check? Otherwise, both checks would run, wouldn't they? I guess that would not be intended.

File: Jamulus.pro [hunk 20]
```diff
@@ -93,10 +93,29 @@ win32 {
...
     contains(CONFIG, "jackonwindows") {
-        message(Using Jack instead of ASIO.)
-
-        !exists("C:/Program Files (x86)/Jack/includes/jack/jack.h") {
-            message(Warning: jack.h was not found at the usual place, maybe jack is not installed)
+        contains(QT_ARCH, "i386") {
+            !exist("C:/Program Files (x86)") {
+                message ("Cross compilation build")
+                programfilesdir = "C:/Program Files (x86)"
+                !exists("$${"programfilesdir"}/JACK2/include/jack/jack.h") {
```
Comment (hoffie) [inline Jamulus.pro:100]: `$${"programfilesdir"}` -- this quoting looks surprising to me, but I don't claim to be a `qmake` expert. I would have expected `$${programfilesdir}` similar to `$${libjackname}` below. Is this necessary, if so, why?

This affects this line and some lines further down.

File: Jamulus.pro [hunk 21]
```diff
@@ -93,10 +93,29 @@ win32 {
...
+                    message("Warning: jack.h was not found at the usual place, maybe JACK2 32 bits is not installed to cross compile.")
+                }
```
Comment (hoffie) [inline Jamulus.pro:102]: It looks like the `exists` block is required in all three code paths. Also, it seems to be identical as variables are used (which is good :)). Maybe this can be condensed to a single check after the last block?

`message("Warning: jack.h was not found in the expected location ($${programfilesdir}). Ensure that the right JACK2 variant is installed (32bit vs. 64bit).")`

File: Jamulus.pro [hunk 22]
```diff
@@ -93,10 +93,29 @@ win32 {
...
+            }
+            !exist("C:/Program Files") {
```
[the remark this answers is not in the document]
Comment (jujudusud) [reply Jamulus.pro]: 86c02e43

File: Jamulus.pro [hunk 23]
```diff
@@ -93,10 +93,29 @@ win32 {
 
     # replace ASIO with jack if requested
     contains(CONFIG, "jackonwindows") {
-        message(Using Jack instead of ASIO.)
-
-        !exists("C:/Program Files (x86)/Jack/includes/jack/jack.h") {
-            message(Warning: jack.h was not found at the usual place, maybe jack is not installed)
+        contains(QT_ARCH, "i386") {
+            !exist("C:/Program Files (x86)") {
+                message ("Cross compilation build")
```
[the remark this answers is not in the document]
Comment (jujudusud) [reply Jamulus.pro]: 86c02e43

File: Jamulus.pro (hunk 20 above)
Comment (jujudusud) [reply Jamulus.pro]: 86c02e43

File: Jamulus.pro (hunk 19 above)
Comment (jujudusud) [reply Jamulus.pro]: If QT_ARCH is set to i386, it is a x86 native or a x64 cross compile for 32 bit. It should work like that. lets see wha append when @henkdegroot builds.

File: Jamulus.pro (hunk 21 above)
Comment (jujudusud) [reply Jamulus.pro]: The check is identical but the message really different. Don't know if it is better like that.

File: Jamulus.pro [hunk 24]
```diff
@@ -94,28 +94,39 @@ win32 {
     # replace ASIO with jack if requested
     contains(CONFIG, "jackonwindows") {
         contains(QT_ARCH, "i386") {
-            message("Native i386 build")
-            libjackname = libjack.lib
+            !exist("C:/Program Files (x86)") {
+                message ("Cross compilation build")
+                programfilesdir = "C:/Program Files (x86)"
```
Comment (pljones) [inline Jamulus.pro:99]: You're in a block that's tested for "not exists" on this directory.  I think you have the logic wrong.

File: Jamulus.pro (hunk 19 above)
Comment (jujudusud) [reply Jamulus.pro]: Adding an else at last.

File: Jamulus.pro (hunk 21 above)
Comment (jujudusud) [reply Jamulus.pro]: 9a5c412a

File: Jamulus.pro (hunk 24 above)
Comment (jujudusud) [reply Jamulus.pro:99]: Your right. my bad.
7f243127

**Review by henkdegroot — APPROVED** [review]

**Comment by henkdegroot** [comment]
FYI, I tested these scenario's on my win10 64-bit machine:

For testing I updated the Jamulus.pro CONFIG section and added the "jackonwindows" option.
The below has been tested running the windows powershell script to build the application and generate the win installer.

No JACK2 installed: 
Validate both x86_64 and i386 report the correct message about missing JACK2.
Both options generate the message about missing JACK2.

Only JACK2 64-bit installed:
Validate x86_64 does not show missing JACK2 warning.
Validate i386 still generates the missing JACK2 warning.
Both working as intended.

JACK2 64 & 32 bit installed:
Validate x86_64 does not show missing JACK2 warning.
Validate i386 does not show missing JACK2 warning.
Both working as intended.

Validate build is successfull and Jamulus works with JACK2.
Working as intended, Jamulus can even connect to both JACK2 versions (32 and 64).

Well done @jujudusud

**Comment by jujudusud** [comment]
Special thanks @henkdegroot for testing and also thanks a lot @hoffie and @pljones for your patience ;-)

I think it is now really ready to be merged as it does what it stands for. :-)

**Review by hoffie — APPROVED** [review]
Thanks! Code looks good to me now, thanks for the extensive testing @henkdegroot!

Although the changes look non-invasive and only touch the jack* logic, I'm not sure if we should risk pushing it to 3.8.0.

I have therefore added the 3.8.1 milestone.

**Review by pljones — APPROVED** [review]

**Comment by jujudusud** [comment]
@ann0see this one should also ne merged if there is a RC2

**Comment by ann0see** [comment]
This depends on what the other @jamulussoftware/maindevelopers say.

**Comment by hoffie** [comment]
> @ann0see this one should also be merged if there is a RC2

I'd say: No.

While a lot has been merged post-rc1, all of it was either merged to avoid regressions being introduced by 3.8.0 (e.g. delay pan config persistence) or because it is clearly expected not to affect the final binaries (e.g. clang Github actions).

As said, this PR looks non-breaking, looks to be limited to jackonwindows and is therefore unlikely to affect official binaries. However, it still touches code which is run on every build, so I'd personally defer it to 3.8.1.

There's already 7 issues/PRs marked for 3.8.1, so I guess we could release a 3.8.1 really soonish after 3.8.0 (without running a *mandatory* translation round). So, that'd be my preference. If other developers think different, I'd be ok with trying to stuff it into 3.8.0 as well.

**Comment by pljones** [comment]
I think 3.8.1 would be better, as we could also then automate the builds, with any luck.

Then have some fun getting them into a single Windows installer...

**Comment by ann0see** [comment]
Merged. 

Further todo items as I can read from above:

- [ ] Improved Windows installer: check for JACK if it is a non ASIO build: The magic is here: https://github.com/jamulussoftware/jamulus/blob/d6acd63b98ce345c32c5ac87a99e3b4a532928f7/windows/installer.nsi#L368-L392
- [ ] Added automatic windows build for JACK

This checklist can be copied to an issue or other place
